config/routes.rb
Friends::Application.routes.draw do
  get "home/index"
  get "/add_circle/:id" => 'circles#add_circle', :as => 'add_circle'
  get "/create_circle/:friendship/:circle" => 'circles#create_circle', :as => 'create_circle'
  get "/accept_friend/:friendship/" => 'friendships#accept_friend', :as => 'accept_friend'
  
  devise_for :users
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

   root 'users#index'
   resources :users
   resources :friendships
   resources :circles

end

app/models/circle.rb
class Circle < ActiveRecord::Base
	belongs_to :user
	has_and_belongs_to_many :friendships
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
	belongs_to :user
  belongs_to :friend, :class_name => "User"
  has_and_belongs_to_many :circles
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :friendships, :conditions => {:status => "accepted"}
	has_many :pending_friendships, :class_name => "Friendship", :conditions => {:status => "pending"}
	has_many :requested_friendships, :class_name => "Friendship", :conditions => {:status => "requested"}
	has_many :accepted_friendships, :class_name => "Friendship", :conditions => {:status => "accepted"}
	has_many :circles
  has_many :friends, :through => :accepted_friendships
  # has_many :requested_friends, :through => :requested_friendships
  # has_many :pending_friends, :through => :pending_friendships
  has_many :inverse_friendships, :class_name => "Friendship", :foreign_key => "friend_id"
  has_many :inverse_friends, :through => :inverse_friendships, :source => :user
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :authenticate_user!
end

app/controllers/circles_controller.rb
class CirclesController < ApplicationController
	def index
	end
	def show
		@circle_id=params[:id]
		@circle=Circle.find(@circle_id)
	end
	def new
		@circles=Circle.all
		@new_circle=current_user.circles.new
	end
	def create
		# binding.pry
		@new_circle=current_user.circles.create(:name => params[:circle][:name])
		redirect_to :action => 'new'
	end
	def destroy
		Circle.find(params[:id]).delete
		redirect_to :action => 'new'
	end
	def add_circle
		@friendship=Friendship.find(params[:id])
		@circles=current_user.circles.all
	end
	def create_circle
		@friendship=Friendship.find(params[:friendship])
		@circle=Circle.find(params[:circle])
		@friendship.circles << @circle
		redirect_to :action => 'new'
	end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
	def create
    @friendship1 = current_user.friendships.build(:friend_id => params[:friend_id],:status => "requested")
    @friendship2= User.find(params[:friend_id]).friendships.build(:friend_id => current_user.id, :status => "pending")
    if @friendship1.save && @friendship2.save
      flash[:notice] = "Added friend."
      redirect_to root_url
    else
      flash[:error] = "Unable to add friend."
      redirect_to root_url
    end
  end
  
  def destroy
    @friendship1 = Friendship.find(params[:id])
    @friendship2 = Friendship.where(:user_id => @friendship1.friend_id, :friend_id => @friendship1.user_id).first
    @friendship1.destroy
    @friendship2.destroy
    flash[:notice] = "Removed friendship."
    redirect_to current_user
  end
  def accept_friend
    @accept1=Friendship.find(params[:friendship])
    @accept1.status="accepted"
    @accept2=Friendship.where(:user_id => @accept1.friend_id, :friend_id => @accept1.user_id).first
    @accept2.status="accepted"
    @accept1.save && @accept2.save
    redirect_to root_url
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	redirect_to(:controller =>'users', :action=>'index')
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index
    @users = User.all
  end
  
  def show
    @user = current_user
    @invitations = current_user.pending_friendships
  end
  
  def new
    @user = User.new
  end
  
  # def create
  #   @user = User.new(params[:user])
  #   if @user.save
  #     session[:user_id] = @user.id
  #     flash[:notice] = "Thank you for signing up! You are now logged in."
  #     redirect_to root_url
  #   else
  #     render :action => 'new'
  #   end
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/circles_helper.rb
module CirclesHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/circles/add_circle.html.erb
<h2>Click on any of the circles to add in them</h2>
<%@circles.each do |circle|%>
	<%if !circle.friendships.exists?(@friendship)%>
		<%=link_to circle.name,create_circle_path(:friendship => @friendship.id,:circle => circle.id)%><br>
	<%end%>
<%end%>

app/views/circles/new.html.erb
<div class="container">
	<%=link_to "Go back",users_path(:id=>current_user.id)%><br>
	<%= form_for @new_circle do |f|%>
		<%=f.text_field :name, :class=> 'form-control', :placeholder => 'Circle Name'%><br>
		<%=f.submit "Add",:class=>'btn btn-primary'%>
	<%end%>
	<br>
	<h2>List of circles</h2>
	<ol>
		<%@circles.each do |circle|%>
			<li><b><%=link_to circle.name,circle_path(:id=>circle.id)%></b>
			<%=link_to "Remove circle",circle_path(:id=>circle.id),:method => "delete"%></li><br>
		<%end%>
	</ol>
</div>

app/views/circles/show.html.erb
<div class="container">
	<%=link_to "Go Back",new_circle_path%>
	<h2>Friends in <%=@circle.name%></h2>
	<%@circle.friendships.each do |friend|%>
	<%=User.find(friend.friend_id).email%>
	<%end%>
</div>

app/views/home/index.html.erb
<h2>List of users</h2>
<div id="users">
<% for user in @users %>
  <div class="user">
  	<%if user!=current_user && !current_user.friends.exists?('id'=>user.id) %>
	    <p>
	      <strong><%=h user.email %></strong>
	      <%= link_to "Add Friend", friendships_path(:friend_id => user), :method => :post %>
	      <div class="clear"></div>
	    </p>
	  <%end%>
  </div>
<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Friends</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/index.html.erb
<div class="container">
	<div class="header-links text-center">
		<%= link_to "My friends", user_path(:id => current_user.id)%>
		<%=link_to "Log out", destroy_user_session_path, :method => :delete %>
	</div>
	<h2>List of users that you can add!</h2>
	<div id="users">
	<% for user in @users %>
	  <div class="user">
	  	<%if user!=current_user && !current_user.friendships.exists?('id'=>user.id) %>
	  	<%f = Friendship.find_by(:friend_id => user.id)%>
		    <div class="row">
		    	<div class="col-lg-1"></div>
		      <div class="col-lg-5"><strong><%=h user.email %></strong></div>
		      <div class="col-lg-5">
		      <%if current_user.friends.include?(user)%>
		      	Friends already
		      <%elsif  current_user.requested_friendships.include?(f)%>
		      	Requested 
		      <%elsif current_user.pending_friendships.include?(f)%>
		      	Sent you a friend request
		      <%else%>
		      	<%= link_to "Add Friend", friendships_path(:friend_id => user), :method => :post %>
		      <%end%>
		     </div>
		    </div>
		      <div class="clear"></div>
		    </p>
		  <%end%>
	  </div>
	<% end %>
	</div>
</div>

app/views/users/show.html.erb
<div class="container">
	<div class="header-links text-center">
		<%= link_to "Home",root_path%>
		<%= link_to "Create circle",new_circle_path%>
	</div>
	<p>User: <%=h @user.email %></p>
	<h2>Friends</h2>
	<ul>
	  <% for friendship in @user.friendships %>
	    <li>
	      <%=h friendship.friend.email %>
	      (<%= link_to "Remove Friend", friendship, :method => :delete %>)
	      (<%= link_to "Add to circle", add_circle_path(:id => friendship.id) %>)
	    </li>
	  <% end %>
	</ul>
	<h2> Invitations</h2>
	<% @invitations.each do |invitation|%>
		Friend request from id : <%=link_to invitation.id,accept_friend_path(:friendship => invitation.id)%>
	<%end%>
</div>